flags: {}
packages:
- '.'
- location:
    git: https://github.com/cauterize-tools/cauterize.git
    commit: bcd3ffefc677a02c0bbf95e7e806d1bf0b33d6dd
extra-deps:
  - s-cargot-0.1.0.0
resolver: lts-3.16
